app = "traitorsfantasydraft-web"

[build]
  dockerfile = "Dockerfile.frontend"
  [build.args]
    VITE_POCKETBASE_URL = "https://api.traitorsfantasydraft.online"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
